//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingStoreDesktop.Models.SystemModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatLich
    {
        public string MaDL { get; set; }
        public string MaKH { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayCuoi { get; set; }
        public Nullable<System.DateTime> NgayTrangTri { get; set; }
        public Nullable<System.TimeSpan> ThoiGianTrangTri { get; set; }
        public Nullable<bool> TrangThaiDuyet { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
