//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingStoreDesktop.Models.SystemModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public string MaNV { get; set; }
        public string MaHD { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.TimeSpan> ThoiGianDen { get; set; }
        public Nullable<System.TimeSpan> ThoiGianDi { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
